# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/temp/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/temp/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib D:/temp/project_2/project_2.srcs/sources_1/new/temp_generate.v
read_xdc D:/temp/project_2/project_2.srcs/constrs_1/new/temp.xdc
set_property used_in_implementation false [get_files D:/temp/project_2/project_2.srcs/constrs_1/new/temp.xdc]

synth_design -top temp_generate -part xc7z020clg400-1
write_checkpoint -noxdef temp_generate.dcp
catch { report_utilization -file temp_generate_utilization_synth.rpt -pb temp_generate_utilization_synth.pb }
