# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/5Project/PYNQ/Air-conditioning-infrared-remote-control/project_38kkkkkCopy/project_38kkkkk.cache/wt [current_project]
set_property parent.project_path D:/5Project/PYNQ/Air-conditioning-infrared-remote-control/project_38kkkkkCopy/project_38kkkkk.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/5Project/PYNQ/Air-conditioning-infrared-remote-control/ip_repo_IR_1.2/IR_1.2
  d:/5Project/PYNQ/Air-conditioning-infrared-remote-control/ip_repo_IR_1.1/IR_1.1
  d:/5Project/PYNQ/Air-conditioning-infrared-remote-control/ip_repo_IR/IR_1.0
} [current_project]
read_verilog -library xil_defaultlib D:/5Project/PYNQ/Air-conditioning-infrared-remote-control/hongwai_new.v
read_xdc D:/5Project/PYNQ/Air-conditioning-infrared-remote-control/project_38kkkkkCopy/project_38kkkkk.srcs/constrs_1/new/123.xdc
set_property used_in_implementation false [get_files D:/5Project/PYNQ/Air-conditioning-infrared-remote-control/project_38kkkkkCopy/project_38kkkkk.srcs/constrs_1/new/123.xdc]

synth_design -top hongwai -part xc7z020clg400-1
write_checkpoint -noxdef hongwai.dcp
catch { report_utilization -file hongwai_utilization_synth.rpt -pb hongwai_utilization_synth.pb }
