# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/temp/ip_repo/edit_myip_v1_0.cache/wt [current_project]
set_property parent.project_path D:/temp/ip_repo/edit_myip_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/temp/ip_repo/myip_1.0 [current_project]
read_verilog -library xil_defaultlib D:/temp/ip_repo/myip_1.0/hdl/myip_v1_0.v
synth_design -top myip_v1_0 -part xc7z020clg400-1
write_checkpoint -noxdef myip_v1_0.dcp
catch { report_utilization -file myip_v1_0_utilization_synth.rpt -pb myip_v1_0_utilization_synth.pb }
