set_property PACKAGE_PIN V17 [get_ports IR_out]
set_property PACKAGE_PIN D19 [get_ports key_1]
set_property PACKAGE_PIN D20 [get_ports key_2]
set_property PACKAGE_PIN R14 [get_ports led_out]
set_property IOSTANDARD LVCMOS33 [get_ports IR_out]
set_property IOSTANDARD LVCMOS33 [get_ports key_1]
set_property IOSTANDARD LVCMOS33 [get_ports key_2]
set_property IOSTANDARD LVCMOS33 [get_ports led_out]
