# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/project_38kkkkk/project_38kkkkk.cache/wt [current_project]
set_property parent.project_path G:/project_38kkkkk/project_38kkkkk.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib G:/project_38kkkkk/project_38kkkkk.srcs/sources_1/new/hongwai.v
read_xdc G:/project_38kkkkk/project_38kkkkk.srcs/constrs_1/new/123.xdc
set_property used_in_implementation false [get_files G:/project_38kkkkk/project_38kkkkk.srcs/constrs_1/new/123.xdc]

synth_design -top hongwai -part xc7z020clg400-1
write_checkpoint -noxdef hongwai.dcp
catch { report_utilization -file hongwai_utilization_synth.rpt -pb hongwai_utilization_synth.pb }
