# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/111.xdc

# Block Designs: bd/design_IR_test/design_IR_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test || ORIG_REF_NAME==design_IR_test}]

# IP: bd/design_IR_test/ip/design_IR_test_processing_system7_0_0/design_IR_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_processing_system7_0_0 || ORIG_REF_NAME==design_IR_test_processing_system7_0_0}]

# IP: bd/design_IR_test/ip/design_IR_test_IR_v1_0_0_0/design_IR_test_IR_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_IR_v1_0_0_0 || ORIG_REF_NAME==design_IR_test_IR_v1_0_0_0}]

# IP: bd/design_IR_test/ip/design_IR_test_processing_system7_0_axi_periph_0/design_IR_test_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_IR_test_processing_system7_0_axi_periph_0}]

# IP: bd/design_IR_test/ip/design_IR_test_rst_processing_system7_0_100M_0/design_IR_test_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_IR_test_rst_processing_system7_0_100M_0}]

# IP: bd/design_IR_test/ip/design_IR_test_auto_pc_0/design_IR_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_auto_pc_0 || ORIG_REF_NAME==design_IR_test_auto_pc_0}]

# XDC: bd/design_IR_test/ip/design_IR_test_processing_system7_0_0/design_IR_test_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_IR_test_processing_system7_0_0 || ORIG_REF_NAME==design_IR_test_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_IR_test/ip/design_IR_test_rst_processing_system7_0_100M_0/design_IR_test_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_IR_test_rst_processing_system7_0_100M_0}]

# XDC: bd/design_IR_test/ip/design_IR_test_rst_processing_system7_0_100M_0/design_IR_test_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_IR_test_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_IR_test_rst_processing_system7_0_100M_0}]

# XDC: bd/design_IR_test/ip/design_IR_test_rst_processing_system7_0_100M_0/design_IR_test_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/design_IR_test/ip/design_IR_test_auto_pc_0/design_IR_test_auto_pc_0_ooc.xdc

# XDC: bd/design_IR_test/design_IR_test_ooc.xdc
