webtalk_init -webtalk_dir D:\\5Project\\11111\\temp\\yaokongqi\\yaokongqi.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ÐÇÆÚÒ» ÁùÔÂ 11 14:13:07 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6roeq3agl4ta8mngse8ogm6m7d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1528696935108" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1528696935108"
webtalk_add_data -client sdk -key uid -value "1528696989643" -context "sdk\\\\bsp/1528696989643"
webtalk_add_data -client sdk -key hwid -value "1528271843003" -context "sdk\\\\bsp/1528696989643"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1528696989643"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1528696989643"
webtalk_add_data -client sdk -key uid -value "1528696995521" -context "sdk\\\\application/1528696995521"
webtalk_add_data -client sdk -key hwid -value "1528271843003" -context "sdk\\\\application/1528696995521"
webtalk_add_data -client sdk -key bspid -value "1528696989643" -context "sdk\\\\application/1528696995521"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1528696995521"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1528696995521"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1528696995521"
webtalk_transmit -clientid 3291913190 -regid "" -xml D:\\5Project\\11111\\temp\\yaokongqi\\yaokongqi.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\5Project\\11111\\temp\\yaokongqi\\yaokongqi.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\5Project\\11111\\temp\\yaokongqi\\yaokongqi.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
